### ISSUE TITLE
minimega: disk info

### ISSUE THREAD

**Issue by csymonds** [sandia-minimega/minimega#1120] opened 2018-06-13 23:08 UTC
It would be useful to have disk info also report the number of partitions on the disk image.

**Comment by jcrussell** [comment] 2018-06-14 17:49
`disk info` wraps `qemu-img` which doesn't report partition information.

From what I can tell, the easiest way to get partition info is as follows:

```
qemu-nbd -c /dev/nbd0 /path/to/a.qcow2
sfdisk -d /dev/nbd0
qemu-nbd -d /dev/nbd0
```

We talked about adding a `disk partition` API in the past (#534) but decided it wasn't worth adding. We could make `disk inject` fail if there is more than one partition and you don't specify one.

**Comment by jcrussell** [comment] 2018-06-14 18:15
Actually, we're already supposed to fail if the disk has more than one partition and a partition isn't specified:

https://github.com/sandia-minimega/minimega/blob/master/src/minimega/disk.go#L201

**Comment by jcrussell** [comment] 2018-08-21 23:55
Closing this since we fixed the cause of this request (not returning an error when the partition is unspecified and there is more than one partition in f5edd12a4d1e10964afbd95de6184891d1331015).

@csymonds: reopen if you object.

**Closed by jcrussell** 2018-08-21 23:55 UTC
