### ISSUE TITLE
Error using serial communications for miniccc w/ Windows VM

### ISSUE THREAD

**Issue by activeshadow** [sandia-minimega/minimega#585] opened 2016-06-29 03:40 UTC
I have a Windows Server 2012 and Windows 7 VM image w/ miniccc and virtio drivers installed. I have a scheduled task triggered at startup that executes `C:\miniccc.exe -serial \\.\Global\cc`. All is well in the beginning... when the VMs are started from scratch I see them via `cc clients`. However, if I have to restart one of the VMs (say to change the hostname, finalize the installation of a server role, etc), I get the following error in minimega:

```
ERROR server.go:237: extra data in buffer
```

After this, the client no longer shows up in `cc clients` and doing a reboot of the VMs doesn't fix anything. Trying to run `C:\miniccc.exe -serial \\.\Global\cc` in one of the VMs after this happens results in the following output:

```
ERROR client.go:132: Insufficient system resources exist to complete requested service.
ERROR client.go:122: Used to indicate that an operation cannot continue without blocking for I/O.
ERROR tunnel.go:80: ListenAndServe: io: read/write on closed pipe
```

Please advise. Thx!

Note: I have not tried using miniccc over serial on Linux VMs, so I don't know if this is _just_ a Windows issue or a serial transport issue in general.

**Comment by mkunz7** [comment] 2016-09-06 21:35
Haven't attempted this yet, but have you tried using a random sleep delay running miniccc to avoid flooding mini and to wait for hardware to be recognized by windows?

```
C:\run.bat
set /a rand=%random% %%90+30
timeout %rand%
```

Also have you enabled more than 4 serial ports on your host? I'm not sure how miniccc handles a connection to the host. But by default linux only supports 4 serial ports. 
(Windows supports 256)
```
sudo bash
nano /etc/grub/default
[find this line GRUB_CMDLINE_LINUX_DEFAULT=
and add this to that variable
8250.n_uarts = 256
save]
update-grub
reboot
```

ERROR client.go:132: Insufficient system resources exist to complete requested service.
This is just trying to connect locally to a minimega socket and failing. Are you able to use minimega -e or minimega -attach after rebooting the vms?

**Comment by djfritz** [comment] 2016-10-12 19:09
Looking into this now

**Comment by activeshadow** [comment] 2017-02-25 19:02
Any movement on this? Just curious... looks like there is since a milestone target has been set. Is there a branch I can test with?

Full transparency, I have not tried any of @mkunz7's suggestions yet... 🤔

**Comment by djfritz** [comment] 2017-03-02 19:52
Returning to this. This is a booger of a bug because of the way virtio treats the transport - it's a regular file so there aren't flush ioctls to reset the state. This may require some sync magic on minimega's part, but that just feels wrong...

**Comment by jcrussell** [comment] 2017-04-17 23:39
@activeshadow: I've been tweaking the CC layer quite a bit in the last week. I added some synchronization between ron/miniccc that may solve this issue. If it's easy for you to build from my fork and test this, please let me know if it works! It at least doesn't break anything in our minitests.

**Comment by mkunz7** [comment] 2017-06-03 09:19
Can confirm broken on linux as well.

@jcrussell it doesn't look like your branch fixed it with a ubuntu guest or a windows guest, vm's still aren't able to reconnect after reboot.

Also I'm not sure if this is by design, but there's no way to delete tunnels, which is annoying.

**Comment by jcrussell** [comment] 2018-09-21 22:50
@activeshadow, @mkunz7: can you try with #1177?

**Comment by activeshadow** [comment] 2018-09-22 14:30
> On Sep 21, 2018, at 16:50, Jon Crussell <notifications@github.com> wrote:
> 
> @activeshadow, @mkunz7: can you try with #1177?
> 

Hmmm... I’ll have to see if I can get my hands on a Windows image these days.

**Comment by jcrussell** [comment] 2018-09-28 18:14
Tested with a debian VM, this should be fixed. Will reopen if not.

**Closed by jcrussell** 2018-09-28 18:14 UTC
