### ISSUE TITLE
minimega: panic on 'read' with whitespace

### ISSUE THREAD

**Issue by djfritz** [sandia-minimega/minimega#149] opened 2015-03-31 14:38 UTC
root@ccc1:~# cat > foo.mm << EOF
> echo foo
> 
> echo bar
> EOF
@jcrussell @floren 

root@ccc1:~# ./minimega

minimega$ read foo.mm 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x43eb24]

goroutine 28 [running]:
main.hasCommand(0x0, 0x949f70, 0x4, 0x0)
        /home/fritz/repos/minimega/src/minimega/misc.go:292 +0xf4
main.cliRead(0xc20804f950, 0xc2080645a0)
        /home/fritz/repos/minimega/src/minimega/misc_cli.go:142 +0x887
minicli.func·009()
        /home/fritz/repos/minimega/src/minicli/minicli.go:123 +0x69
created by minicli.ProcessCommand
        /home/fritz/repos/minimega/src/minicli/minicli.go:132 +0x214

**Comment by djfritz** [comment] 2015-03-31 14:41
github ate my formatting...

If you have a blank line in a minimega script, it now panics.

Working before:
https://github.com/sandia-minimega/minimega/commit/437db60c1db8183a9eafc2520639d68a0ddfa20a

This is probably broken in other places that can ingest blank lines (command socket, meshage). We need a unit test for ingesting a blank command if that's the real culprit here.

**Comment by jcrussell** [comment] 2015-03-31 15:13
Found this when working on ticket-86. Fixed in that pull request, caused by the new recursive check for read.

**Comment by djfritz** [comment] 2015-03-31 15:14
Can we port the fix here in some fashion? We need this fixed immediately to get existing environments running.

**Comment by jcrussell** [comment] 2015-03-31 15:17
Yeah, will do.

**Comment by jcrussell** [comment] 2015-03-31 15:21
https://github.com/jcrussell/minimega/tree/hotfix

**Closed** 2015-03-31 15:29 UTC
Labels: bug, triage
