### ISSUE TITLE
New web interface crashes Firefox and other issues with usability

### ISSUE THREAD

**Issue by mkunz7** [sandia-minimega/minimega#315] opened 2015-09-04 20:29 UTC
Steps to reproduce:
1. Start minimega
2. Launch 30 VM's (less will probably cause the issue as well)
3. Open the web interface in firefox
4. Select more than 6 VMs to be displayed 

I made video
http://ku.nz/proof.zip
download, extract and drag into a browser to play

Other issues I think we should consider changing
-> Why can't I click on a VM in the VM List to launch no vnc?
-> Why isn't there a disk column?
-> Why can't I click on the VNC screenshot to launch the VM? Could we just rename it VNC Sessions and get rid of the connect button?
-> Sometimes when I click on Connect it doesn't open a new tab for novnc and I have to click it twice or three times
-> Sorting by IP address doesn't work
-> Can Network Graph be moved to a different tab? I think it really clutters the information

**Comment by djfritz** [comment] 2015-09-04 20:46
@jfktrey

**Comment by rkaack** [comment] 2015-09-04 22:03
Confirmed as well on OSX with Firefox. Memory grows and Firefox becomes unusable. Will provide screenshot if needed.

**Comment by jfktrey** [comment] 2015-09-05 22:31
Firefox issue makes sense. The way that new data is automatically pulled and integrated into the dataTable isn't optimized, so that's likely the root cause. FF tends to leak memory more readily.

Other issues are definitely noted and will be addressed. Some should go away as the different widgets become more integrated. Network Graph should be able to be moved easily.

**Comment by djfritz** [comment] 2015-09-05 23:47
Hold off on moving things until it's discussed here.

**Comment by djfritz** [comment] 2015-09-08 19:55
@jfktrey make this the priority

**Comment by mkunz7** [comment] 2015-10-01 22:22
It's really annoying to have multiple vm-#'s and have to highlight over each to find out which node it is on.

Can we either include a hostname next to the Screenshot Name? Or a link from VM List to launch NoVNC? Or both?

**Comment by jcrussell** [comment] 2016-03-21 21:49
@mkunz7 -- we just merged the PR that addressed some of these concerns. Thoughts?

**Comment by mkunz7** [comment] 2016-03-21 23:07
Skiing in Colorado right now. I'm excited to check it out when I get back.

**Comment by mkunz7** [comment] 2016-04-05 03:35
VNC no longer works in firefox. 

After clicking connect to a vnc session.  I'm getting either a 
```Server disconnected (code: 1006)```
or a 
```noVNC ready: native WebSockets, canvas rendering```

Memory usage still rises and doesn't clean up when I right click connect and open a new tab and then close it. 

Seems to be working fine in chrome. Admittedly haven't given things a through run through. Are we planning on addressing some of the other ui issues mentioned above?

**Comment by djfritz** [comment] 2016-04-05 13:34
@mkunz7 

Is your problem occuring only after attempting vnc use? Is this your issue:

https://github.com/kanaka/noVNC/issues/431

We're using a "stable" novnc (0.4), and this bug didn't get fixed until >0.5.1. Can you drop in a new novnc in misc/web/novnc and test again? If that fixes (at least part of) your issues, we'll update novnc in the repo.

**Comment by djfritz** [comment] 2016-04-05 13:35
As for the other UI nits. Yes - we're getting there. We don't have enough help and the web frontend just gets kicked down the priority list every time.

**Comment by mkunz7** [comment] 2016-04-05 23:18
The memory usage growing is just from not being able to open novnc. Idle on the page seems to be fine without memory growth. Firefox just doesn't load vnc at all anymore. 

I'm not opposed to getting the latest.

I grabbed a copy off kanaka's website and put in the novnc folder ran all.bash started web and launched 70 vms. Vms are booted, but when you click connect now in chrome and firefox it just says "loading".

Web console says

```http://REMOVED:9001/novnc/include/jsunzip.js Failed to load resource: the server responded with a status of 404 (Not Found)````

My bad our vnc.html needed to be updated manually to have our changes merged with v5's since they changed how they handle variables and we have a hardcoded /novnc. This lead to

```Uncaught Error: noVNC no longer supports base64 WebSockets.  Please use the binary subprotocol instead.```

Removing the line forcing base64 causes it to never progress past starting vnc handshake in the dev log.

Changing 'base64' to 'binary' causes it to hang at starting vnc handshake in the dev log.

I'm guessing there's some sort of compile magic that needs to be done when making qemu to support binary websockets. Anyone got any input?

**Comment by djfritz** [comment] 2016-04-06 14:22
https://github.com/sandia-minimega/minimega/blob/master/src/minimega/tunnel.go

We use the base64 encoding scheme in order to provide the VNC gateway and in order to intercept keyboard/mouse events (https://github.com/sandia-minimega/minimega/blob/master/src/minimega/tunnel.go#L69). 

If we're going to upgrade, we'll need to replace our tunnel function with one that supports the binary interface.

@jcrussell thoughts?

**Comment by jcrussell** [comment] 2016-04-13 23:43
Probably doable, I can start looking into this.

**Comment by djfritz** [comment] 2016-06-08 20:19
Merging this into #524 and #566

**Closed by djfritz** 2016-06-08 20:19 UTC
Labels: bug, triage
