### ISSUE TITLE
container fail to mount cgroups

### ISSUE THREAD

**Issue by x64x6a** [sandia-minimega/minimega#433] opened 2016-03-02 02:01 UTC
On latest debian, minimega would fail to mount minicgroup:
```
$ vm config filesystem /root/containerfs
$ vm launch container foo
2016/03/01 18:39:12 ERROR container.go:253: cgroup mount: device or resource busy
2016/03/01 18:39:12 ERROR container.go:721: cannot launch container VMs -- cgroups failed to initialize
2016/03/01 18:39:12 ERROR vm.go:487: write instance state file: open /tmp/minimega/0/state: no such file or directory
Error (debian): cannot launch container VMs -- cgroups failed to initialize
```

Unable to mount as well:
```
# mount -t cgroup minicgroup foo/
mount: minicgroup is already mounted or /tmp/foo busy
```

Issue may be caused by how systemd handles cgroups.

**Comment by djfritz** [comment] 2016-03-02 14:17
Looking into this today.

**Comment by x64x6a** [comment] 2016-03-02 19:51
I'd hate to say it, but maybe it would be easier to use systemd?

I think that [libcontainer](https://github.com/opencontainers/runc/tree/master/libcontainer) from the Open Container Initiative utilizes systemd.
Perhaps we should look into their implementation or use libcontainers?

**Comment by djfritz** [comment] 2016-03-02 21:06
@floren @jcrussell @cdshann 

I had a rather large response to the idea of using systemd. Instead, I'll just say no. No systemd.

**Comment by cdshann** [comment] 2016-03-02 23:42
I think it is inevitable that we will need to adopt systemd. Pretty much the only holdouts from embracing systemd in the container ecosystem is docker (and minimega of course).

Some reading for thought:
https://github.com/coreos/rkt/blob/master/Documentation/using-rkt-with-systemd.md
https://lwn.net/SubscriberLink/676831/bc927a5c0955d2b7/ (Systemd vs docker)

**Comment by djfritz** [comment] 2016-03-03 14:39
I honestly can't tell if you're serious.

**Comment by djfritz** [comment] 2016-03-03 15:07
@x64x6a what are you doing to reproduce your error? Here's what I get:

    root@node:~# mount | grep cgroup
    none on /sys/fs/cgroup type tmpfs (rw)
    systemd on /sys/fs/cgroup/systemd type cgroup (rw,noexec,nosuid,nodev,none,name=systemd)
    root@node:~# mkdir -p /tmp/minimega/cgroup
    root@node:~# mount -t cgroup minicgroup /tmp/minimega/cgroup
    root@node:~# mount | grep cgroup
    none on /sys/fs/cgroup type tmpfs (rw)
    systemd on /sys/fs/cgroup/systemd type cgroup (rw,noexec,nosuid,nodev,none,name=systemd)
    minicgroup on /tmp/minimega/cgroup type cgroup (rw)
    root@node:~# 

And again on a node without systemd but still with another root cgroup mount:

    root@ccc22:~# mount | grep cgroup
    cgroup on /sys/fs/cgroup type cgroup (rw,relatime,cpuset,cpu,cpuacct,blkio,memory,devices,freezer,net_cls,perf_event,net_prio,clone_children)
    root@ccc22:~# mount -t cgroup minicgroup /tmp/minimega/cgroup/
    root@ccc22:~# mount | grep cgroup
    cgroup on /sys/fs/cgroup type cgroup (rw,relatime,cpuset,cpu,cpuacct,blkio,memory,devices,freezer,net_cls,perf_event,net_prio,clone_children)
    minicgroup on /tmp/minimega/cgroup type cgroup (rw,relatime,cpuset,cpu,cpuacct,blkio,memory,devices,freezer,net_cls,perf_event,net_prio,clone_children)
    root@ccc22:~#

**Comment by x64x6a** [comment] 2016-03-03 18:29
Everything I tested on was on fresh installs of the following on virtual machines.

##### Debian unstable
```
root@debian:~# cat /etc/*release
PRETTY_NAME="Debian GNU/Linux stretch/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@debian:~# uname -a
Linux debian 4.4.0-1-amd64 #1 SMP Debian 4.4.2-3 (2016-02-21) x86_64 GNU/Linux
root@debian:~# mount -t cgroup minicgroup /tmp/minimega/cgroup/
mount: minicgroup is already mounted or /tmp/minimega/cgroup busy
root@debian:~# 
```

##### Debian 8
```
root@debian:~# cat /etc/*release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@debian:~# uname -a
Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) x86_64 GNU/Linux
root@debian:~# mount -t cgroup minicgroup /tmp/minimega/cgroup/
mount: minicgroup is already mounted or /tmp/minimega/cgroup busy
root@debian:~# 
```

##### Ubuntu 15 Desktop
```
root@ubuntu:~# cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=15.04
DISTRIB_CODENAME=vivid
DISTRIB_DESCRIPTION="Ubuntu 15.04"
NAME="Ubuntu"
VERSION="15.04 (Vivid Vervet)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 15.04"
VERSION_ID="15.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
root@ubuntu:~# uname -a
Linux ubuntu 3.19.0-15-generic #15-Ubuntu SMP Thu Apr 16 23:32:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
root@ubuntu:~# mount  -t cgroup minicgroup /tmp/minimega/cgroup/
mount: minicgroup is already mounted or /tmp/minimega/cgroup busy
root@ubuntu:~# 
```


I just made some different tests, also with fresh ISOs.

##### Ubuntu 15 Server
```
root@ubuntu:~# cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=15.04
DISTRIB_CODENAME=vivid
DISTRIB_DESCRIPTION="Ubuntu 15.04"
NAME="Ubuntu"
VERSION="15.04 (Vivid Vervet)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 15.04"
VERSION_ID="15.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
root@ubuntu:~# uname -a
Linux ubuntu 3.19.0-15-generic #15-Ubuntu SMP Thu Apr 16 23:32:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
root@ubuntu:~# mkdir -p /tmp/minimega/cgroup
root@ubuntu:~# mount -t cgroup minicgroup /tmp/minimega/cgroup
mount: minicgroup is already mounted or /tmp/minimega/cgroup busy
root@ubuntu:~#
```

##### Ubuntu 14 Server
```
root@ubuntu:~# cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"
NAME="Ubuntu"
VERSION="14.04.3 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.3 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
root@ubuntu:~# uname -a
Linux ubuntu 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
root@ubuntu:~# mkdir -p /tmp/minimega/cgroup
root@ubuntu:~# mount -t cgroup minicgroup /tmp/minimega/cgroup
root@ubuntu:~# mount | grep minicgroup
minicgroup on /tmp/minimega/cgroup type cgroup (rw)
root@ubuntu:~#
```

So I guess it works fine in Ubuntu 14?
Not sure what version of Debian made the change though.

**Comment by djfritz** [comment] 2016-03-16 13:03
By build of debian unstable appears to work... I'll rebuild from the bleeding edge of debian and try again.

**Comment by djfritz** [comment] 2016-03-16 14:17
Works for me on what appears to be the same debian unstable as yours. I just can't seem to reproduce your issues anywhere.

    root@(none):~# cat /etc/*release
    PRETTY_NAME="Debian GNU/Linux stretch/sid"
    NAME="Debian GNU/Linux"
    ID=debian
    HOME_URL="https://www.debian.org/"
    SUPPORT_URL="https://www.debian.org/support"
    BUG_REPORT_URL="https://bugs.debian.org/"
    root@(none):~# uname -a
    Linux (none) 4.4.0-1-amd64 #1 SMP Debian 4.4.4-2 (2016-03-09) x86_64 GNU/Linux
    root@(none):~# mount -t cgroup minicgroup /tmp/minimega/cgroup
    root@(none):~# mount | grep cgroup
    cgroup on /sys/fs/cgroup type cgroup (rw,relatime,cpuset,cpu,cpuacct,blkio,memory,devices,freezer,net_cls,perf_event,net_prio,pids)
    minicgroup on /tmp/minimega/cgroup type cgroup (rw,relatime,cpuset,cpu,cpuacct,blkio,memory,devices,freezer,net_cls,perf_event,net_prio,pids)
    root@(none):~#

**Comment by x64x6a** [comment] 2016-03-16 20:27
Well I feel special now.  I'll try another few attempts with latest.

**Comment by x64x6a** [comment] 2016-03-17 18:45
I installed weekly from http://cdimage.debian.org/cdimage/weekly-builds/amd64/iso-dvd/ on a vm and upgraded to unstable.  

Still no bueno:
```
root@debian:~# cat /etc/*release
PRETTY_NAME="Debian GNU/Linux stretch/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@debian:~# uname -a
Linux debian 4.4.0-1-amd64 #1 SMP Debian 4.4.4-2 (2016-03-09) x86_64 GNU/Linux
root@debian:~# mount -t cgroup minicgroup /tmp/minimega/cgroup
mount: minicgroup is already mounted or /tmp/minimega/cgroup busy
root@debian:~#
```

No clue why we're getting different responses.

**Comment by x64x6a** [comment] 2016-03-17 19:06
Am I missing a dependency or something maybe?

I made a dependency script for minimega.  Am I missing something here?
```
#!/bin/sh

# Install packages
sudo apt-get -y install \
	gcc \
	git \
	libreadline-dev \
	libpcap-dev \
	openvswitch-ipsec \
	python-pip \
	qemu-system \
	qemu-kvm
sudo pip install jinja2

# Install go
sudo wget https://storage.googleapis.com/golang/go1.6.linux-amd64.tar.gz -O /tmp/go.tar.gz
sudo tar -C /usr/local -xzf /tmp/go.tar.gz
sudo bash -c 'echo "export PATH=\$PATH:/usr/local/go/bin
" >> /etc/profile'

# Install updated dnsmasq
sudo apt-get -y remove dnsmasq
sudo wget http://www.thekelleys.org.uk/dnsmasq/dnsmasq-2.75.tar.xz -O /tmp/dnsmasq-2.75.tar.xz \
	&& sudo tar xvf /tmp/dnsmasq-2.75.tar.xz -C /tmp \
	&& sudo make install -C /tmp/dnsmasq-2.75
sudo reboot
```
Not sure what else would be different.

**Comment by djfritz** [comment] 2016-03-18 12:59
Can you find any stackexchange, etc. posts about this? Is anyone else having this problem?

**Comment by djfritz** [comment] 2016-03-24 17:24
I can't seem to reproduce this and we're against a wall with the release. I'm closing this until it becomes a reproducible issue.

**Closed by djfritz** 2016-03-24 17:24 UTC

**Comment by x64x6a** [comment] 2016-03-29 20:36
That's cool.  I found similar issues that others were having with mount, but I couldn't replay their issues.  ..
