### ISSUE TITLE
Issue with Running Minimega VM and Assigning IP to VM

### ISSUE THREAD

**Issue by mzinfobeyond** [sandia-minimega/minimega#1518] opened 2023-08-30 16:02 UTC
Hello,

I am a new user of Minimega and have been following the [quickstart](https://minimega.org/articles/tutorials/quickstart.article) to run miniccc VM. Here are the steps I followed:

- I created the miniccc.kernel and miniccc.initrd pair as mentioned in Step 1. I copied these files to /tmp/minimega/files.
- Following Step 2, I started Minimega.
- I configured and started the VM using the following commands:
`minimega[minimega]$ vm config kernel miniccc.kernel`
`minimega[minimega]$ vm config initrd miniccc.initrd`
`minimega[minimega]$ vm config net LAN`
`minimega[minimega]$ tap create LAN ip 10.0.0.1/24`
`user: mega_tap0`
`minimega[minimega]$ dnsmasq start 10.0.0.1 10.0.0.2 10.0.0.254`
`minimega[minimega]$ vm launch kvm test`
`minimega[minimega]$ vm start test`
- However, when I checked for the assigned IP using the command:
`minimega[minimega]$ .annotate false .columns name,state,ip vm info`
I found that the IP field for the "test" VM was empty:
`name | state   | ip`
`test | RUNNING | []`
- Additionally, when I started Miniweb and attempted to connect to the VNC, I encountered the following result:
![minimega_vnc](https://github.com/sandia-minimega/minimega/assets/141345186/046e4bfc-eb49-4fae-a81b-44814e5833c9)

I would greatly appreciate your assistance in resolving this issue. Thank you in advance for your help.

**Comment by jacdavi** [comment] 2023-09-09 00:52
Hi. I believe the issue is with creating the vm using `vmbetter`. It looks like the VM isn't able to boot properly because some things are missing. @aherna any insight? I can't seem to build a booting VM either using the quickstart steps.

The vnc session seems to be working fine. That's just the output from the VM.

**Comment by mzinfobeyond** [comment] 2023-09-11 23:02
Hello @jacdavi,

I appreciate your response. I am eagerly awaiting the solution to the issue mentioned earlier.

Additionally, could you kindly provide me with a source for a VM image that I can utilize with minimega?

Thank you once again!

**Comment by jacdavi** [comment] 2023-09-11 23:09
@mzinfobeyond minimega supports booting VMs in the `qcow2` which might be easier to work with. You can find steps here: https://www.sandia.gov/minimega/module-12-building-a-vm-with-kvm/

You can also search how to create qcow2 images. This seems like a simple option, though I've never used it: https://github.com/openstack/diskimage-builder

**Comment by jacdavi** [comment] 2024-01-04 19:54
Hi @mzinfobeyond were you ever able to get a working image? I'll go ahead and close the issue unless there's anything else you need help with.

**Comment by jacdavi** [comment] 2024-06-20 18:37
Going to go ahead and close this, but please reach out if you need more help (we'll try our best to respond)

**Closed by jacdavi** 2024-06-20 18:37 UTC
Labels: question
